# Generated by Django 3.1.4 on 2021-01-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dislikes',
        ),
    ]
