# Generated by Django 3.1.4 on 2021-01-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_dislikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
